#!/usr/bin/env python3.10
from pathlib import Path

from coordinates import get_coordinates
from weather_api_service import get_weather
from weather_formatter import format_weather
from history import save_weather, JSONFileWeatherStorage
from exceptions import CantGetCoordinates, WeatherApiServiceError


def main(place: str):
    try:
        coordinates = get_coordinates(place)
    except CantGetCoordinates:
        print('Не удалось получить координаты')
        exit(1)
    
    try:
        weather = get_weather(coordinates)
    except WeatherApiServiceError:
        print('Не удалось получить погоду по координатам')
        exit(1)

    print(format_weather(weather))

    save_weather(
        weather,
        JSONFileWeatherStorage(Path.cwd() / 'history.json')
    )


if __name__ == '__main__':
    place = input('Введите название местности: ')
    main(place)
